AppBundle\Entity\Card:
    properties:
        isActive:
            - NotBlank: ~
        serialNumber:
            - NotBlank: ~
            - Length:
                min: 13
                max: 13
        createdAt:
            - NotBlank: ~
        updatedAt:
            - NotBlank: ~

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - Email: ~